@terceros
Feature: Gestión de terceros en Siigo
  Como usuario autenticado
  Quiero crear un cliente tercero
  Para registrarlo correctamente en el sistema

  Background:
    Given Userqa abre la aplicación Siigo en la página de inicio de sesión
    When el ingresa las credenciales válidas e inicia sesión

  @crearTercero
  Scenario Outline: Crear cliente tercero exitosamente
    When el crea un cliente tercero con los siguientes datos:
      | tipoPersona   | tipoIdentificacion   | numeroIdentificacion   | dv   | codSucursal   | nombres   | apellidos   | razonSocial   | ciudad   | direccion   | indicativo   | telefono   | extension   | correo   | tipoIva   | indicativoFactura   | telefonoFactura   | codigoPostal   | nombreContacto   | apellidoContacto   | emailContacto   | cargo   | indicativoContacto   | telefonoContacto   |
      | <tipoPersona> | <tipoIdentificacion> | <numeroIdentificacion> | <dv> | <codSucursal> | <nombres> | <apellidos> | <razonSocial> | <ciudad> | <direccion> | <indicativo> | <telefono> | <extension> | <correo> | <tipoIva> | <indicativoFactura> | <telefonoFactura> | <codigoPostal> | <nombreContacto> | <apellidoContacto> | <emailContacto> | <cargo> | <indicativoContacto> | <telefonoContacto> |
    Then el usuario al finalizar el proceso, el sistema debe mostrar "<resultado>"
    And el usuario debe validar que el cliente tercero se haya creado correctamente en el sistema en el API relation con el status code "<statusCode>"

    Examples:
      | tipoPersona | tipoIdentificacion                                              | numeroIdentificacion | dv | codSucursal | nombres | apellidos | razonSocial | ciudad   | direccion    | indicativo | telefono | extension | correo         | tipoIva               | indicativoFactura | telefonoFactura | codigoPostal | nombreContacto | apellidoContacto | emailContacto    | cargo   | indicativoContacto | telefonoContacto | resultado                                                                                                                                | statusCode |
      | Es persona  | Pasaporte                                                       | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Documento de identificación extranjero                          | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Permiso especial de permanencia PEP                             | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Sin identificación del exterior o para uso definido por la DIAN | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Registro civil                                                  | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Cédula de ciudadanía                                            | Random               |  1 |         101 | Juan    | Perez     | test        | Sabaneta | cl45a #46-78 |         57 |  2859984 |       401 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Cédula de ciudadanía                                            |              1234567 |  1 |         101 | Juan    | Perez     | test        | Sabaneta | cl45a #46-78 |         57 |  2859984 |       401 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | La identificación del tercero que estas creando ya existe.                                                                               |        400 |
      | Empresa     | NIT                                                             | Random               |  1 |         102 | Pepito  | Perez     | Empresa SAS | Sabaneta | cl45a #46-78 |         57 |  2859984 |       402 | test1@test.com | Responsable de IVA    |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Tarjeta de extranjería                                          | Random               |  1 |         103 | Juan    | Perez     |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       403 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tercero guardado exitosamente                                                                                                            |        200 |
      | Es persona  | Cédula de ciudadanía                                            |               123456 |  1 |         105 |         |           |             | Sabaneta | cl45a #46-78 |         57 |  2859984 |       405 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gamil.com | Gerente |                104 |          7852385 | Tienes campos obligatorios sin completar.                                                                                                |        400 |
      | Es persona  | Cédula de ciudadanía                                            |               123456 |  1 |         105 | Pepito  | Perez     | Empresa SAS | Sabaneta | cl45a #46-78 |         57 |  2859984 |       405 | test1@         | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gmail.com | Gerente |                104 |          7852385 | Introduce un correo electrónico válido: ejemplo@email.com                                                                                |        400 |
      | Es persona  | Cédula de ciudadanía                                            | qwwweee              |  1 |         105 | Pepito  | Perez     | Empresa SAS | Sabaneta | cl45a #46-78 |         57 |  2859984 |       405 | test1@test.com | No responsable de IVA |               102 |         2587474 |        58485 | Pepito         | Garcia           | pepito@gmail.com | Gerente |                104 |          7852385 | El campo 'Identificación' no tiene un formato correcto, solo se acepta valores numéricos y valor diferente a '0' en la primera posición. |        400 |
